// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcP8huU5ghM-eGRGmRRdXSmBEj5CE1SCo',
    appId: '1:696943933969:web:3bb47578470cca02f54fb0',
    messagingSenderId: '696943933969',
    projectId: 'flight-app-80866',
    authDomain: 'flight-app-80866.firebaseapp.com',
    storageBucket: 'flight-app-80866.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmdViEINqmKfK72JlSHGbb_WqrLsS6Nk',
    appId: '1:696943933969:android:8316e3cba6cff2b9f54fb0',
    messagingSenderId: '696943933969',
    projectId: 'flight-app-80866',
    storageBucket: 'flight-app-80866.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YDcZ3DfIuIyBhVR4CAAnNyBQHiqtp7o',
    appId: '1:696943933969:ios:d4b5b8d9f868e821f54fb0',
    messagingSenderId: '696943933969',
    projectId: 'flight-app-80866',
    storageBucket: 'flight-app-80866.appspot.com',
    iosClientId: '696943933969-8ekuafu6ec1a6m8n9l00ofk53ccuk2g1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flightApp',
  );
}
